Output short circuit attributes
alliander-opensource/power-grid-model pull request #219
Opened 2023-03-14 09:28 UTC by nitbharambe

2023-03-15 13:32 UTC, petersalemink95 commented
Seems logical to me, I've requested @TonyXiang8787 's review to double check

2023-03-15 14:26 UTC, nitbharambe commented
Right now it is:

base  -- |--> branch 
              |--> shortcircuitbranch
        
 
Is it a good choice to do this way instead?:
base --> branch  --|--> PowerFlowbranch
                               |--> shortcircuitbranch
                           
Then they would share output variables, one issue of having a separate but same `get_null_output()` function will be resolved. But the meaning behind these current and voltages are different

2023-03-16 07:33 UTC, petersalemink95 commented on code_generation/data/attribute_classes/output.json
> +                    "names": ["i_from"],
I'd like to have single values not written as a list, so:
`"names": "i_from",`

Happen on more places ;)

2023-03-16 08:23 UTC, petersalemink95 commented
@nitbharambe answer to your suggestion to have:
"ShortCircuitBranchOutput and PowerFlowOutput derive from BranchOutput"

I don't think that's a good idea, since `BranchOutput` has attributes that are not needed in `ShortCircuitBranchOutput `

2023-03-16 12:48 UTC, TonyXiang8787 requested changes
@nitbharambe two TODO's:

1. add angles to all current results (branch, branch3, appliance)
2. update the documentation in the component table. For each component, use three separate tables: input/update, steady-state output, short circuit output

2023-03-19 20:28 UTC, TonyXiang8787 requested changes
@nitbharambe some open points:

1. In all input attribute tables, remove the column `input`. This does not make sense as it will always have a check sign.
2. Add a separate section between `Component Type Hierarchy and Graph Data Model` and `Components` to explain the structure of the datasets, including the concepts of dataset, component, attribute and value. As we have described in https://alliander.atlassian.net/wiki/spaces/SASOG/pages/3385131970/Glossary
3. In that section explain the current supported dataset types, namely `input`, `update`, `sym_output`, `asym_output`, `sym_sc_output`, `asym_sc_output`. Explain their intended usage.

2023-03-22 08:14 UTC, TonyXiang8787 approved these changes

2023-03-22 09:30 UTC, merged